import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(`flex bg-black h-full`, inter.className)}>
        <Sidebar />

        <main
          className="flex-1 
          min-h-screen
          bg-black
          ml-0
          pr-3
          py-3
          rounded-lg 
          h-screen"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
