import "./globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";

import Sidebar from "@/components/organisms/Sidebar";
import SupabaseProvider from "@/providers/supabaseContextProvider";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={twMerge(`flex bg-black h-full`, inter.className)}>
        <SupabaseProvider>
          <Sidebar />
          <main
            className="
          flex-1
          min-h-screen
          bg-black
          ml-0
          pr-2
          py-2
          rounded-lg
          h-screen
          "
          >
            {children}
          </main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
